bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

homing/urls.py
from . import views
from django.urls import path
from .views import *

urlpatterns = [
    path("", views.DogList.as_view(), name="homing"),
    path('int:<slug:slug>/', views.DogDetail.as_view(), name='dog_detail'),
    path('like/<slug:slug>', views.DogLike.as_view(), name='dog_like'),
    path('delete_comment/<int:comment_id>',
         views.delete_comment, name='delete_comment'),
    path('edit_comment/<int:pk>', views.EditComment.as_view(),
         name='edit_comment'),
    path('add/', views.add_dog, name='add_dog'),
    path('edit/<int:dog_id>/', views.edit_dog, name='edit_dog'),
    path('delete/<int:dog_id>/', views.delete_dog, name='delete_dog'),
]

wicklow_animal_welfare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("home.urls"), name="home"),
    path('products/', include('products.urls')),
    path('homing/', include('homing.urls'), name="homing-urls"),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('summernote/',  include('django_summernote.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'wicklow_animal_welfare.views.handler404'

homing/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse

STATUS = ((0, "Draft"), (1, "Published"))
BOOKED = (("Available", "Available"), ("Booked", "Booked"))
SEX = (("Male", "Male"), ("Female", "Female"))
SIZE = (("Small", "Small"), ("Medium", "Medium"), ("Large", "Large"))


class Dog(models.Model):

    dog_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    featured_image = CloudinaryField('image', default='placeholder')
    about = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    booked = models.CharField(max_length=200, choices=BOOKED,
                              default='Available')
    size = models.CharField(max_length=200, choices=SIZE, default=False)
    sex = models.CharField(max_length=200, choices=SEX, default=False)
    likes = models.ManyToManyField(
        User, related_name='dog_like', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.dog_name

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE,
                            related_name="comments")
    username = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

    def get_absolute_url(self):
        """Sets absolute URL"""
        return reverse('dog_detail', args=[self.dog.slug])

homing/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Dog, STATUS, BOOKED, SEX, SIZE, Comment


class DogForm(forms.ModelForm):

    class Meta:
        model = Dog
        fields = '__all__'
    featured_image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

# Comment form


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)

homing/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from .models import *
from .forms import DogForm, CommentForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required


class DogList(generic.ListView):

    model = Dog
    queryset = Dog.objects.filter(status=1).order_by("-created_on")
    template_name = "homing.html"
    paginate_by = 12


class DogDetail(View):

    def get(self, request, slug, *args, **kwargs):

        queryset = Dog.objects.filter(status=1)
        dog = get_object_or_404(queryset, slug=slug)
        comments = dog.comments.order_by("-created_on")
        liked = False
        if dog.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "dog_detail.html",
            {
                "dog": dog,
                "comments": comments,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):

        queryset = Dog.objects.filter(status=1)
        dog = get_object_or_404(queryset, slug=slug)
        comments = dog.comments.order_by("-created_on")
        liked = False
        if dog.likes.filter(id=self.request.user.id).exists():
            liked = True
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.dog = dog
            messages.add_message(request,
                                 messages.INFO, 'Thank you for your comment!')
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "dog_detail.html",
            {
                "dog": dog,
                "comments": comments,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

# View for liking a post


class DogLike(LoginRequiredMixin, View):

    """
    Like/Unlike dog
    """
    def post(self, request, slug, *args, **kwargs):

        dog = get_object_or_404(Dog, slug=slug)
        if dog.likes.filter(id=request.user.id).exists():
            dog.likes.remove(request.user)
            messages.success(request, 'You have unliked this post, thanks!')
        else:
            dog.likes.add(request.user)
            messages.success(request, 'You have liked this post, thanks!')
        return HttpResponseRedirect(reverse('dog_detail', args=[slug]))

# View for deleting logged in user comment


@login_required
def delete_comment(request, comment_id):

    """ Method to delete a comment
    """
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    messages.success(request, 'Your comment was deleted successfully')
    return HttpResponseRedirect(reverse(
        'dog_detail', args=[comment.dog.slug]))

# View for editing logged in user comment


class EditComment(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    """
    Edit comment
    """
    model = Comment
    template_name = 'edit_comment.html'
    form_class = CommentForm
    success_message = 'Your comment was successfully updated'


@login_required
def add_dog(request):

    """ Add a dog to the page """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added dog!')
            return redirect(reverse('homing'))
        else:
            messages.error(request, 'Failed to add dog. Please check form')
    else:
        form = DogForm()

    template = 'add_dog.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_dog(request, dog_id):

    """ Edit a dog profile"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    dog = get_object_or_404(Dog, pk=dog_id)
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES, instance=dog)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated dog!')
            return redirect(reverse('homing'))
        else:
            messages.error(request, 'Failed to update. Please check form')
    else:
        form = DogForm(instance=dog)
        messages.info(request, f'You are editing {dog.dog_name}')

    template = 'edit_dog.html'
    context = {
        'form': form,
        'dog': dog,
    }

    return render(request, template, context)


@login_required
def delete_dog(request, dog_id):

    """ Delete a dog profile """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    dog = get_object_or_404(Dog, pk=dog_id)
    dog.delete()
    messages.success(request, 'Dog deleted!')
    return redirect(reverse('homing'))

homing/templates/add_dog.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Dog Management</h2>
                <h5 class="text-muted">Add a Dog</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_dog' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'homing' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Dog</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

homing/templates/dog_detail.html
{% extends 'base.html' %} 
{%load static%}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div></div>
    </div>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
    <div class="overlay"></div>
    <div class="masthead">
        <div class="container">
            <div class="row g-0">
                <div class="col-md-6 masthead-text">
                    <h1 class="post-title">{{ dog.dog_name }}</h1>
                    <p class="post-subtitle">{{ dog.size}} | {{ dog.created_on }}</p>
                </div>
                <div class="d-none d-md-block col-md-6 masthead-image">
                    {% if "placeholder" in dog.featured_image.url %}
                    <img src="{{ MEDIA_URL }}noimage.png" width="100%">
                    {% else %}
                    <img src=" {{ dog.featured_image.url }}" width="100%">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col card mb-4  mt-3 left  top">
                <div class="card-body">
                    <p class="card-text ">
                        {{ dog.content | safe }}
                    </p>
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_dog' dog.id %}">Edit</a> | 
                            <a class="text-danger" href="{% url 'delete_dog' dog.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <!-- Like button functionality -->
                    <div class="row">
                        <div class="col-1 like">
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'dog_like' dog.slug %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" name="dog_id" value="{{ dog.slug}}" class="btn">
                                    <span> <i class="{% if liked %}fas{% else %}far{% endif %} fa-heart"></i>{{ dog.number_of_likes }}</span>
                                </button>
                            </form>
                            {% else %}
                            <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#like-login"><i class="far fa-heart"></i>{{ dog.number_of_likes }}</button>
                            <!-- Login bootstrap modal-->
                            <div class="modal" id="like-login" tabindex="-1" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Login</h5>
                                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>You must login to like a dog</p>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{% url 'account_login' %}" class="btn btn-primary" aria-label="Login">Login</a>
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                        <!-- Comment numbers -->
                        <div class="col-1 like">
                            {% with comments.count as total_comments %}
                            <strong class="btn"><i class="far fa-comments"></i>
                                {{ total_comments }}</strong>
                            {% endwith %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <!-- Comments posted-->
        <div class="row">
            <div class="col-md-8 card mb-4  mt-3 ">
                <h3>Comments:</h3>
                <div class="card-body">
                    {% for comment in comments %}
                    <div class="comments" style="padding: 10px;">
                        <p class="font-weight-bold">
                            {{comment.name}}
                            <span class="font-weight-normal">
                                {{comment.created_on}}
                            </span> wrote:
                        </p>
                        {{ comment.body | linebreaks }}
                    </div>
                    <!-- Links to edit, delete and login -->
                    {% if user.is_authenticated and user.email == comment.email or user.is_superuser %}
                    <a href="{% url 'edit_comment' comment.id %}" class="btn" aria-label="Go to the Edit Comments Page">Edit</a>
                    <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#delete-comment">Delete</button>
                        <!-- Delete comment bootstrap modal-->
                    <div class="modal" id="delete-comment" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Delete Comment</h5>
                                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to delete your comment?</p>
                                </div>
                                <div class="modal-footer">
                                    <a href="{% url 'delete_comment' comment.pk %}" class="btn btn-primary" aria-label="Delete Comment">Delete</a>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    {% if user.is_authenticated and user.username != comment.name %}
                    <br>
                    {% else %}
                    <a  href="{% url 'account_login' %}" class="btn" aria-label="Go to the Login Page">Please login to edit or delete your comments</a>
                    {% endif %}
                    {% endif %}
                    {% endfor%}
                </div>
            </div>
            <!-- Commenting area for users -->
            <div class="col-md-4 card mb-4  mt-3 ">
                <div class="card-body">
                    {% if user.is_authenticated %}

                    <h3>Leave a comment:</h3>
                    <p>Posting as: {{ user.username }}</p>
                    <form method="post" style="margin-top: 1.3em;">
                        {{ comment_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn">Submit</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

homing/templates/edit_comment.html
{% extends "base.html" %}
{%load static%}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div></div>
    </div>
{% endblock %}

{% block content %}

<!-- Edit Comment Form-->
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn mb-4" type="submit" value="Save">Submit</button>
            </form>
        </div>
    </div>

{%endblock%}

homing/templates/edit_dog.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div></div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Dog Management</h2>
                <h5 class="text-muted">Edit a Dog</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'edit_dog' dog.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'homing' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Update Dog</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

homing/templates/homing.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Dog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for dog in dog_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in dog.featured_image.url %}
                                <img class="card-img-top"
                                    src="{{ MEDIA_URL }}noimage.png">
                                {% else %}
                                <img class="card-img-top" src=" {{ dog.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Sex: {{ dog.sex }}</p>
                                </div>
                            </div>
                            <a href="{% url 'dog_detail' dog.slug  %}" class="post-link">
                                <h2 class="card-title">{{ dog.dog_name }}</h2>
                                <p class="card-text">{{ dog.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ dog.created_on}} <i class="far fa-heart"></i>
                                {{ dog.number_of_likes }}</p>
                            {% if request.user.is_superuser %}
                                <small class="ml-3">
                                    <a href="{% url 'edit_dog' dog.id %}">Edit</a> | 
                                    <a class="text-danger" href="{% url 'delete_dog' dog.id %}">Delete</a>
                                </small>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

homing/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="col-7 col-md-6 my-auto">
            <h1 class="display-4 logo-font text-black">
                Ways to Donate
            </h1>
            <div class="my-5">
                <h4>
                    <a href="{% url 'products' %}" class="shop-now-button btn btn-lg rounded-0 text-uppercase py-3">Donate Now</a>
                </h4>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">

        <!-- Dog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for dog in dog_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in dog.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ dog.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Sex: {{ dog.sex }}</p>
                                </div>
                            </div>
                            <a href="{% url 'dog_detail' dog.slug  %}" class="post-link">
                                <h2 class="card-title">{{ dog.dog_name }}</h2>
                                <p class="card-text">{{ dog.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ dog.created_on}} <i class="far fa-heart"></i>
                                {{ dog.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}